name: Main application

on:
  workflow_dispatch:
  push:
    branches:
      - "main" 
      - "total-normal-pipelines"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  run_server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask werkzeug pycryptodome bcrypt pyAesCrypt rsa flask_login

    - name: Start the server
      run: |
        python3 main.py &
        sleep 3 
        ls -l database.db
        ls -l
        chmod +rw database.db
        ls -l database.db
        whoami

    - name: testing 
      run: |
        whoami
        curl http://127.0.0.1:8000
        curl -X POST \
        http://127.0.0.1:8000/createAccount \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d 'username=test4&password=pass&publicKey=1&signPublicKey=2'

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: error.log
        path: ./error.log
      if: always()