name: Main application

on:
  workflow_dispatch:
  push:
    branches:
      - "main" 
      - "total-normal-pipelines"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  run_server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask werkzeug pycryptodome bcrypt pyAesCrypt rsa flask_login

    - name: Start the server
      run: |
        python3 main.py &
        sleep 3

    - name: testing 
      run: |
        curl http://127.0.0.1:8000
        curl -X POST \
        http://127.0.0.1:8000/createAccount \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        -d 'username=test4&password=pass&publicKey=1&signPublicKey=2'

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: error.log
        path: ./error.log
      if: always()

  run_scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install chromedriver-autoinstaller selenium pyvirtualdisplay

    - name: Installing package list
      run: apt list --installed

    - name: Removing previous Chrome instances on runner 
      run: sudo apt purge google-chrome-stable  

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Run the sender and receiver
      run: |
        python3 selinum_scripts/connection.py
        python3 selinum_scripts/sender.py &
        python3 selinum_scripts/receiver.py

    - name: Capture screenshots
      run: |
        mkdir screenshots
        mv *.png screenshots
      if: always()

    - name: Upload screenshots as artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: screenshots
      if: always()

    - name: Upload logs as artifact
      uses: actions/upload-artifact@v2
      with:
        name: error.log
        path: ./error.log
      if: always()

    - name: Testing if file is created
      run: ls
