
name: Main application

on:
    workflow_dispatch: # Ensure this is correctly indented
    push:
      branches: 
        - "main" 
        - "total-normal-pipelines"
    pull_request:
      branches: 
        - "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install werkzeug
        pip install pycryptodome
        pip install bcrypt
        pip install pyAesCrypt
        pip install rsa
        pip install flask_login
        
    - name: Run the server
      run: python3 main.py


    - name: testing 
      run: |
        curl http://127.0.0.1:8000



      

      
    
        
